def run():
    print()
    print("  ╔══════════════════════════════════════════════════════════════╗")
    print("  ║                        X-DATA CREDITS                       ║")
    print("  ╚══════════════════════════════════════════════════════════════╝")
    print()
    print("  Made by")
    print("    elmuerte")
    print("    Discord: tears.ss")
    print()
    print("  Contributions / Support")
    print("    profane")
    print("    Discord: prfn7 / .w7mpus")
    print()
    print("  ─────────────────────────────────────────────────────────────")
    print("  Thank you for supporting X-Data.")
    print()
    input("  Press Enter...")
